
set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSTEM_NAME i386-elf)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(tools $ENV{HOME}/x-tools/i386-elf)

#set(CMAKE_SYSROOT ${tools}/i486-bezbios-elf)

set(ENV{GCC_EXEC_PREFIX} ${tools}/lib/gcc/)

set(CMAKE_TRY_COMPILE_TARGET_TYPE   STATIC_LIBRARY)

set(CMAKE_C_COMPILER ${tools}/bin/i386-elf-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/i386-elf-g++)

set(CMAKE_C_FLAGS -specs=nano.specs CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET_PROPERTY(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS true)
